module.exports = {
    theme: {
        extend: {
            fontFamily: {
                kalimati: ['Kalimati', 'sans-serif'],
                sans: ['"Nunito Sans"', 'sans-serif'],
            },
        },
    },
    content: ['./src/**/*.{js,jsx,ts,tsx,html}'], // make sure this matches your file structure
    plugins: [],
};

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx,html,css}",
    ],
    theme: {
        extend: {},
    },
    plugins: [],
    safelist: [
        // --- Essential Layout Classes from ChartReportPage.jsx ---
        'flex',
        'h-screen',
        'overflow-hidden', // From main container
        'relative',
        'flex-col',
        'flex-1', // <--- CRITICAL for main content to grow
        'overflow-y-auto',
        'overflow-x-hidden', // From main content wrapper
        'flex-grow', // From the <main> tag

        // --- Sidebar Specific Classes from Sidebar.jsx ---
        'w-64', // Base width
        'lg:w-20', // Collapsed width on large screens
        'lg:sidebar-expanded:!w-64', // Expanded width on large screens
        // '2xl:w-64!', // Re-evaluate if you want this to always be wide at 2xl breakpoint
        'shrink-0', // Prevents sidebar from shrinking
        'p-4', // Padding
        'translate-x-0', // For mobile sidebar visibility
        '-translate-x-64', // For mobile sidebar hidden state
        'lg:static',
        'lg:left-auto',
        'lg:top-auto',
        'lg:translate-x-0', // Resets mobile positioning on desktop
        'h-[100dvh]',
        'overflow-y-scroll',
        'lg:overflow-y-auto',
        'no-scrollbar',
        'transition-all',
        'duration-200',
        'ease-in-out',
        'rounded-r-2xl',
        'shadow-xs',
        // Classes for sidebar links and icons (inspect these if their styling is off)
        'text-sm',
        'font-bold',
        'ml-4',
        'lg:opacity-0',
        'lg:sidebar-expanded:opacity-100',
        '2xl:opacity-100',
        'block',
        'text-gray-800',
        'dark:text-gray-100',
        'truncate',
        'transition',
        'duration-150',
        'hover:text-gray-900',
        'dark:hover:text-white',
        'flex',
        'items-center',
        'shrink-0',
        'fill-current',
        'text-violet-500',
        'text-gray-400',
        'dark:text-gray-500',
        'fill-none',
        'stroke-current',
        'pl-4',
        'pr-3',
        'py-2',
        'rounded-lg',
        'mb-0.5',
        'last:mb-0',
        { pattern: /from-violet-500/, variants: ['dark'] }, // For the gradient background
        { pattern: /to-violet-500/, variants: ['dark'] },   // For the gradient background


        // --- Chart/Text related classes (from previous discussion) ---
        { pattern: /text-(xs|sm|base|lg|xl|2xl|3xl|4xl)/ }, // General font sizes
        { pattern: /font-(normal|medium|semibold|bold)/ },   // General font weights
        'chartjs-tooltip', // If chart tooltips use Tailwind classes

        'chartjs',
        'chartjs-render-monitor',
        'chartjs-tooltip',
        'chartjs-tooltip-title',
        'chartjs-tooltip-body',
        'chartjs-tooltip-footer',
        // Classes related to legends, axes, etc., often generated by Chart.js or its plugins
        // These are examples; inspect your browser's dev tools on localhost to find the exact ones Chart.js uses for font sizes, ticks, etc.
        // For text size issues:
        {
            pattern: /text-(xs|sm|base|lg|xl|2xl|3xl|4xl)/, // if Chart.js sets text sizes via these
        },
        {
            pattern: /font-(normal|medium|semibold|bold)/, // if Chart.js sets font weights
        },
    ],
}